components:
  embedding_retriever:
    init_parameters:
      document_store:
        init_parameters:
          bm25_algorithm: BM25L
          bm25_parameters: {}
          bm25_tokenization_regex: (?u)\b\w\w+\b
          embedding_similarity_function: dot_product
        type: haystack.document_stores.in_memory.document_store.InMemoryDocumentStore
      filters: null
      return_embedding: false
      scale_score: false
      top_k: 10
    type: haystack.components.retrievers.in_memory.embedding_retriever.InMemoryEmbeddingRetriever
  reader:
    init_parameters:
      answers_per_seq: null
      calibration_factor: 0.1
      device: null
      max_batch_size: null
      max_seq_length: 384
      model: deepset/roberta-base-squad2-distilled
      model_kwargs:
        device_map: cpu
      no_answer: true
      score_threshold: null
      stride: 128
      token:
        env_vars:
        - HF_API_TOKEN
        strict: false
        type: env_var
      top_k: 20
    type: haystack.components.readers.extractive.ExtractiveReader
  text_embedder:
    init_parameters:
      batch_size: 32
      device:
        device: cpu
        type: single
      model: sentence-transformers/all-MiniLM-L6-v2
      normalize_embeddings: false
      prefix: ''
      progress_bar: true
      suffix: ''
      token:
        env_vars:
        - HF_API_TOKEN
        strict: false
        type: env_var
      trust_remote_code: false
    type: haystack.components.embedders.sentence_transformers_text_embedder.SentenceTransformersTextEmbedder
connections:
- receiver: embedding_retriever.query_embedding
  sender: text_embedder.embedding
- receiver: reader.documents
  sender: embedding_retriever.documents
max_loops_allowed: 100
metadata: {}
